name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install build dependencies
        run: python -m pip install build ninja cmake

      - name: Install from source
        run: python -m pip install --force-reinstall --no-deps .

      - name: Smoke test import (source build)
        run: python -c "import fuzzycocopython; print(fuzzycocopython.__version__)"

      - name: Uninstall package
        run: python -m pip uninstall -y fuzzycocopython

      - name: Clean previous wheels
        run: python -c "import shutil; shutil.rmtree('dist', ignore_errors=True)"

      - name: Build wheel
        run: python -m build --wheel

      - name: Install from wheel
        run: python -m pip install --force-reinstall --no-deps dist/*.whl

      - name: Smoke test import (wheel)
        run: python -c "import fuzzycocopython; print(fuzzycocopython.__version__)"
